apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 8080  
      nodePort: 30007   

