apiVersion: v1
kind: Service
metadata:
  name: nodeport 
spec:
  type: NodePort
  ports:
  - port: 80          # Port exposed within the cluster
    targetPort: 8080  # Port on the pods
    nodePort: 30001   # Port accessible externally on each node
  selector:
    prt:v1
